const VARIANT = {
  NAVBAR_MENU: "NAVBAR_MENU",
  NAVBAR_MENU_ACTIVE: "NAVBAR_MENU_ACTIVE",
  JUMBOTRON: "JUMBOTRON",
  JUMBOTRON_BOLD: "JUMBOTRON_BOLD",
  FOOTER: "FOOTER",
  CATEGORY_HEADER: "CATEGORY_HEADER",
  PRODUCT_TITLE: "PRODUCT_TITLE",
  PRODUCT_PRICE: "PRODUCT_PRICE",
};

export default {
  VARIANT,
};
