const VARIANT = {
  NAVBAR_MENU: "NAVBAR_MENU",
  NAVBAR_MENU_ACTIVE: "NAVBAR_MENU_ACTIVE",
  JUMBOTRON: "JUMBOTRON",
  JUMBOTRON_BOLD: "JUMBOTRON_BOLD",
  FOOTER: "FOOTER",
  CATEGORY_HEADER: "CATEGORY_HEADER",
  PRODUCT_TITLE: "PRODUCT_TITLE",
  PRODUCT_TITLE_BIG: "PRODUCT_TITLE_BIG",
  PRODUCT_PRICE: "PRODUCT_PRICE",
  BREADCRUMB: "BREADCRUMB",
  BREADCRUMB_ACTIVE: "BREADCRUMB_ACTIVE",
  PRICE: "PRICE",
  SIZE: "SIZE",
  PAGE_TITLE: "PAGE_TITLE",
  INPUT_LABEL: "INPUT_LABEL",
  INPUT_LABEL_ERROR: "INPUT_LABEL_ERROR",
  CART_ITEM_TITLE: "CART_ITEM_TITLE",
  PRODUCT_PRICE_SECONDARY: "PRODUCT_PRICE_SECONDARY",
  ORDER_PRICE_ITEM: "ORDER_PRICE_ITEM",
  ORDER_PRICE_TOTAL: "ORDER_PRICE_TOTAL",
};

export default {
  VARIANT,
};
