const VARIANT = {
  NAVBAR_MENU: "NAVBAR_MENU",
  NAVBAR_MENU_ACTIVE: "NAVBAR_MENU_ACTIVE",
  JUMBOTRON: "JUMBOTRON",
  JUMBOTRON_BOLD: "JUMBOTRON_BOLD",
  FOOTER: "FOOTER",
  CATEGORY_HEADER: "CATEGORY_HEADER",
  PRODUCT_TITLE: "PRODUCT_TITLE",
  PRODUCT_TITLE_BIG: "PRODUCT_TITLE_BIG",
  PRODUCT_PRICE: "PRODUCT_PRICE",
  BREADCRUMB: "BREADCRUMB",
  BREADCRUMB_ACTIVE: "BREADCRUMB_ACTIVE",
  PRICE: "PRICE",
  SIZE: "SIZE",
  PAGE_TITLE: "PAGE_TITLE",
};

export default {
  VARIANT,
};
